-- MySQL Script generated by MySQL Workbench
-- Fri Feb 26 15:02:22 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema jpa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jpa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jpa` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema jpa
-- -----------------------------------------------------
USE `jpa` ;

-- -----------------------------------------------------
-- Table `jpa`.`Agence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jpa`.`Agence` (
  `idAgence` INT NOT NULL AUTO_INCREMENT,
  `adresse` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idAgence`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jpa`.`Vehicule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jpa`.`Vehicule` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `marque` VARCHAR(15) NOT NULL,
  `typeEnergie` VARCHAR(15) NOT NULL,
  `modele` VARCHAR(15) NOT NULL,
  `geolocalisation` VARCHAR(15) NOT NULL,
  `Agence_idAgence` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Vehicule_Agence_idx` (`Agence_idAgence` ASC) VISIBLE,
  CONSTRAINT `fk_Vehicule_Agence`
    FOREIGN KEY (`Agence_idAgence`)
    REFERENCES `jpa`.`Agence` (`idAgence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jpa`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jpa`.`Client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idClient`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
